apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-pipeline-workspace
spec:
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce