apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-dashboard
  labels:
    name: tekton-dashboard
spec:
  ingressClassName: nginx
  rules:
  - host: tkn.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tekton-dashboard
            port: 
              number: 9097