apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dockerhub-build-image
spec:
  params:
    - name: PROJECT
    - name: IMAGE
    - name: TAG
    - name: SOURCE_SUBDIRECTORY
      default: ''
    - name: DOCKER_CREDENTIALS_SECRET
      default: docker-credentials
    - name: VERBOSITY
      default: info
  workspaces:
    - name: source
  steps:
    - name: configure
      image: alpine
      script: |
        #!/bin/sh

        echo -n "{
          \"auths\": {
            \"https://index.docker.io/v1/\": {
              \"auth\": \"$(echo -n $DOCKER_USERNAME:$DOCKER_PASSWORD | base64)\"
            }
          }
        }" > /kaniko/.docker/config.json
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
      env:
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.DOCKER_CREDENTIALS_SECRET)
              key: username
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.DOCKER_CREDENTIALS_SECRET)
              key: password

    - name: build
      image: gcr.io/kaniko-project/executor:v1.7.0
      args:
        - "--dockerfile=$(workspaces.source.path)/$(params.SOURCE_SUBDIRECTORY)/Dockerfile"
        - "--context=dir://$(workspaces.source.path)/$(params.SOURCE_SUBDIRECTORY)"
        - "--destination=$(params.PROJECT)/$(params.IMAGE):$(params.TAG)"
        - "--verbosity=$(params.VERBOSITY)"
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/

  volumes:
    - name: docker-config
      emptyDir: {}