apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline-tekton-rc
spec:
  workspaces:
    - name: source
    - name: ssh-credentials
  params:
    - name: git_repository_name
    - name: git_repository_full_name
    - name: git_repository_url
    - name: git_repository_ssh_url
    - name: git_revision
    - name: git_pull_request_url
    - name: git_pull_request_id
    - name: git_pull_request_sha
    - name: git_pull_request_number
    - name: git_pull_request_base
    - name: truncated_sha
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git_repository_ssh_url)
        - name: revision
          value: $(params.git_pull_request_base)
        - name: subdirectory
          value: $(params.git_repository_name)/$(params.git_pull_request_sha)/source
      workspaces:
        - name: output
          workspace: source
          subPath: src
        - name: ssh-directory
          workspace: ssh-credentials

    - name: compile
      taskRef:
        name: java11-maven-build
      runAfter:
        - fetch-source
      params:
        - name: SUBDIRECTORY
          value: $(params.git_repository_name)/$(params.git_pull_request_sha)/source/
      workspaces:
        - name: source
          workspace: source
          subPath: src
        - name: maven-cache
          workspace: source
          subPath: maven-cache

    - name: build-image
      taskRef:
        name: dockerhub-build-image
      runAfter:
        - compile
      params:
        - name: IMAGE
          value: $(params.git_repository_name)
        - name: TAG
          value: 0.0.$(params.git_pull_request_number)-rc
        - name: SOURCE_SUBDIRECTORY
          value: $(params.git_repository_name)/$(params.git_pull_request_sha)/source/
        - name: PROJECT
          value: <docker hub project name>
      workspaces:
        - name: source
          workspace: source
          subPath: src

    - name: fetch-charts-source
      taskRef:
        name: git-clone
      runAfter:
        - build-image
      params:
        - name: url
          value: $(params.git_repository_ssh_url)
        - name: revision
          value: gh-pages
        - name: subdirectory
          value: $(params.git_repository_name)/gh-pages
      workspaces:
        - name: output
          workspace: source
          subPath: src
        - name: ssh-directory
          workspace: ssh-credentials

    - name: build-chart
      taskRef:
        name: helm-package
      runAfter:
        - fetch-charts-source
      params:
        - name: CHART_NAME
          value: $(params.git_repository_name)
        - name: CHART_VERSION
          value: 0.0.$(params.git_pull_request_number)-rc
        - name: CHART_DIRECTORY
          value: $(params.git_repository_name)/$(params.git_pull_request_sha)/source/.helm
        - name: CHARTS_DIRECTORY
          value: $(params.git_repository_name)/gh-pages/docs/charts
        - name: CHART_REPO_URL
          value: https://<github org name>.github.io/demo-pipeline-tekton/charts
        - name: CONTAINER_IMAGE
          value: <docker hub project name>/$(params.git_repository_name):0.0.$(params.git_pull_request_number)-rc
      workspaces:
        - name: source
          workspace: source
          subPath: src

    - name: push-chart
      taskRef:
        name: git-cli
      runAfter:
        - build-chart
      params:
        - name: GIT_USER_NAME
          value: <name>
        - name: GIT_USER_EMAIL
          value: <email>
        - name: GIT_SCRIPT
          value: |
            git add .
            git commit -m "build chart: $(params.git_repository_name)-0.0.$(params.git_pull_request_number)-rc"
            git push origin HEAD:gh-pages
      workspaces:
        - name: source
          workspace: source
          subPath: src/$(params.git_repository_name)/gh-pages
        - name: ssh-directory
          workspace: ssh-credentials
  finally:
    - name: clean-source
      taskRef:
        name: clean-source
      params:
        - name: directory
          value: /workspace/source/$(params.git_repository_name)/$(params.git_pull_request_sha)
      workspaces:
        - name: source
          workspace: source
          subPath: src