apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-webhook
spec:
  serviceAccountName: github-webhook
  triggers:
    - triggerRef: github-pull-request
    - triggerRef: github-merged
    - triggerRef: github-taged