apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
data:
  secretToken: <your webhook github token here>
---
apiVersion: v1
kind: Secret
metadata:
  name: github
type: Opaque
data:
  token: <your user api github token here>
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
type: Opaque
data:
  username: <your username>
  password: <your password>
---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-credentials
data:
  id_rsa: <your base64 id_rsa>
  known_hosts: <your base64 known_hosts>