apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-taged
spec:
  interceptors:
    - ref:
        name: "github"
        kind: ClusterInterceptor
        apiVersion: triggers.tekton.dev
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["create"]
    - ref:
        name: 'cel'
      params:
        - name: 'filter'
          value: "body.ref_type in ['tag']"
  bindings:
    - ref: github-taged
      kind: TriggerBinding
  template:
    ref: github-taged